Write-Output uninstalling programs...
Get-appxpackage *Microsoft.WindowsCamera* | remove-appxpackage
Get-AppxPackage *Microsoft.WindowsCalculator* | Remove-AppxPackage
Get-Appxpackage *MicrosoftTeams_22115.300.1313.2464_x64__8wekyb3d8bbwe* | Remove-AppxPackage
Get-Appxpackage *Microsoft.YourPhone* | Remove-AppxPackage
Get-Appxpackage *Microsoft.MicrosoftEdge.Stable* | Remove-AppxPackage
Get-Appxpackage *Microsoft.XboxGameOverlay* | Remove-AppxPackage
Get-Appxpackage *Microsoft.XboxGameUI* | Remove-AppxPackage
Get-Appxpackage *Microsoft.Todos* | Remove-AppxPackage
Get-Appxpackage *Microsoft.MicrosoftStickyNotes* | Remove-AppxPackage
Get-Appxpackage *Microsoft.Windows.Cortana* | Remove-AppxPackage
Get-Appxpackage *Clipchamp.Clipchamp* | Remove-AppxPackage
Get-Appxpackage *Microsoft.WindowsStore* | Remove-AppxPackage
Get-Appxpackage *Microsoft.PowerAutomateDesktop* | Remove-AppxPackage
Get-Appxpackage *Microsoft.Windows.Photos* | Remove-AppxPackage
Get-Appxpackage *MicrosoftTeams* | Remove-AppxPackage
Get-Appxpackage *Microsoft.ZuneVideo* | Remove-AppxPackage
Get-Appxpackage *Microsoft.ZuneMusic* | Remove-AppxPackage
Get-Appxpackage *Microsoft.WindowsSoundRecorder* | Remove-AppxPackage
Get-Appxpackage *Microsoft.WindowsFeedbackHub* | Remove-AppxPackage
Get-Appxpackage *microsoft.windowscommunicationsapps* | Remove-AppxPackage
Get-Appxpackage *Microsoft.WindowsCalculator* | Remove-AppxPackage
Get-Appxpackage *Microsoft.ScreenSketch* | Remove-AppxPackage
Get-Appxpackage *Microsoft.MicrosoftStickyNotes* | Remove-AppxPackage
Get-Appxpackage *Microsoft.MicrosoftSolitaireCollection* | Remove-AppxPackage
Get-Appxpackage *Microsoft.MicrosoftOfficeHub* | Remove-AppxPackage
Get-Appxpackage *Microsoft.Getstarted* | Remove-AppxPackage
Get-Appxpackage *Microsoft.GamingApp* | Remove-AppxPackage